### ISSUE TITLE
Remove templating (Blaze) of dependencies?

### ISSUE THREAD

**Issue by gaetandezeiraud** [scholtzm/meteor-steam#1]
Hi, 
Why not remove `steam_configure.html` and `steam_configure.js` in order to remove Blaze (templating) of dependencies? For developers who uses VueJS or React?

Thanks.

**Comment by scholtzm** [comment]
Unfortunately, I don't work on this package anymore.

In case you need to strip these files, you will have to create a fork and use that.

**Comment by gaetandezeiraud** [comment]
Thanks for your answer.
See https://github.com/Exoway/meteor-steam and https://github.com/Exoway/meteor-accounts-steam

In order to remove Blaze and underscore.
Thanks.
